name: Build Slides

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@main
        with:
          persist-credentials: false
          submodules: true  # TODO remove this if not using submodules in Hexo

      - name: Install 🔧
        run: yarn install

      - name: Build 🏗️
        run: |
          yarn clean
          yarn build

      - name: Deploy to GH Pages 🚀
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: public
          